### ISSUE TITLE
Training for Image -> Scene graph

### ISSUE THREAD

**Issue by drewhayward** [deeplab-ai/atr-net#3]
I would like to use your model to process a set of raw images into scene graphs. It is unclear to me  which tasks I have to pipeline in order to process a raw image all the way to a scene graph.

What are the steps to pretrain on VG200 and then run scene graph generation on a new set of images?

**Comment by nickgkan** [comment]
Hi Drew,

In this case, you have to train an object detector on VG200 first
`python3 main.py --dataset=VG200 --task=objdet --model=object_detector`
and then a scene graph generator
`python3 main.py --dataset=VG200 --task=predcls --model=atr_net`

Training on predcls forces the model to learn to filter background relationships.

Now you have all you need. Unfortunately, you have to wrap up the two models yourself in order to infer new images. Having detected object boxes and labels, you can compute all the different types of features atr-net demands, see data_loading_utils for help.

**Comment by drewhayward** [comment]
Thanks!

**Comment by alice-cool** [comment]
> 
> 
> Thanks!

Dear scholar,
 I also want to apply the pretrained atr-net model to new raw images(but my task is only to get scene graph to deal with other tasks), so I think creating false annotation to model(because model needs annotations,but raw images didn't have annotations), and get the net's output. In this way, the code only has little modification. 
![图片](https://user-images.githubusercontent.com/16870890/136693933-1750e857-0f68-468c-ab11-bee6929adec8.png)
